name:                 root-finding
version:              1.0.0.0
visibility:           public
id:                   root-finding-1.0.0.0-inplace
key:                  root-finding-1.0.0.0-inplace
license:              MIT
maintainer:           ehsan.tc.evol@gmail.com
author:               ehsan1381
abi:                  inplace
exposed:              True
exposed-modules:      Bisection
import-dirs:
    /home/ehsan/Documents/test-problems/haskell/HASKELL/root-finding/dist-newstyle/build/x86_64-linux/ghc-9.10.3/root-finding-1.0.0.0/build

library-dirs:
    /home/ehsan/Documents/test-problems/haskell/HASKELL/root-finding/dist-newstyle/build/x86_64-linux/ghc-9.10.3/root-finding-1.0.0.0/build

library-dirs-static:
    /home/ehsan/Documents/test-problems/haskell/HASKELL/root-finding/dist-newstyle/build/x86_64-linux/ghc-9.10.3/root-finding-1.0.0.0/build

dynamic-library-dirs:
    /home/ehsan/Documents/test-problems/haskell/HASKELL/root-finding/dist-newstyle/build/x86_64-linux/ghc-9.10.3/root-finding-1.0.0.0/build

data-dir:
    /home/ehsan/Documents/test-problems/haskell/HASKELL/root-finding/.

hs-libraries:         HSroot-finding-1.0.0.0-inplace
depends:              base-4.20.2.0-127e
haddock-interfaces:
    /home/ehsan/Documents/test-problems/haskell/HASKELL/root-finding/dist-newstyle/build/x86_64-linux/ghc-9.10.3/root-finding-1.0.0.0/doc/html/root-finding/root-finding.haddock

haddock-html:
    /home/ehsan/Documents/test-problems/haskell/HASKELL/root-finding/dist-newstyle/build/x86_64-linux/ghc-9.10.3/root-finding-1.0.0.0/doc/html/root-finding
